//
//  MightyMetUI.swift
//  MightyMetUI
//
//  Created by Justin Bane on 2/5/17.
//  Copyright © 2017 . All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//



import UIKit

public class MightyMetUI : NSObject {

    //// Cache

    private struct Cache {
        static let red: UIColor = UIColor(red: 0.676, green: 0.073, blue: 0.073, alpha: 1.000)
        static let yellow: UIColor = UIColor(red: 0.987, green: 1.000, blue: 0.000, alpha: 1.000)
        static let fuscia: UIColor = UIColor(red: 1.000, green: 0.000, blue: 0.413, alpha: 1.000)
        static let transparent: UIColor = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 0.156)
        static let lime: UIColor = UIColor(red: 0.000, green: 1.000, blue: 0.108, alpha: 1.000)
        static let electricBlue: UIColor = UIColor(red: 0.000, green: 0.974, blue: 1.000, alpha: 1.000)
        static let blue: UIColor = UIColor(red: 0.000, green: 0.070, blue: 1.000, alpha: 1.000)
        static let darkBlue: UIColor = MightyMetUI.blue.withBrightness(0.3)
        static let darkRed: UIColor = MightyMetUI.red.withBrightness(0.3)
        static let yellowOrange: UIColor = MightyMetUI.yellow.withHue(0.1)
        static let darkFuscia: UIColor = MightyMetUI.fuscia.withBrightness(0.4)
        static let darkRedWhiteColor: UIColor = UIColor(red: 0.972, green: 0.000, blue: 0.000, alpha: 1.000)
        static let darkRedWhiteOnColor: UIColor = UIColor(red: 0.882, green: 0.000, blue: 0.000, alpha: 1.000)
        static let redYellow: CGGradient = CGGradient(colorsSpace: nil, colors: [MightyMetUI.red.cgColor, MightyMetUI.yellow.cgColor] as CFArray, locations: [0.26, 1])!
    }

    //// Colors

    public dynamic class var red: UIColor { return Cache.red }
    public dynamic class var yellow: UIColor { return Cache.yellow }
    public dynamic class var fuscia: UIColor { return Cache.fuscia }
    public dynamic class var transparent: UIColor { return Cache.transparent }
    public dynamic class var lime: UIColor { return Cache.lime }
    public dynamic class var electricBlue: UIColor { return Cache.electricBlue }
    public dynamic class var blue: UIColor { return Cache.blue }
    public dynamic class var darkBlue: UIColor { return Cache.darkBlue }
    public dynamic class var darkRed: UIColor { return Cache.darkRed }
    public dynamic class var yellowOrange: UIColor { return Cache.yellowOrange }
    public dynamic class var darkFuscia: UIColor { return Cache.darkFuscia }
    public dynamic class var darkRedWhiteColor: UIColor { return Cache.darkRedWhiteColor }
    public dynamic class var darkRedWhiteOnColor: UIColor { return Cache.darkRedWhiteOnColor }

    //// Gradients

    public dynamic class var redYellow: CGGradient { return Cache.redYellow }

    //// Drawing Methods

    public dynamic class func drawMultiSelector(frame: CGRect = CGRect(x: 0, y: 0, width: 345, height: 345), bPMAngle: CGFloat = 0, pitchAngle: CGFloat = 0) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!

        //// Group
        //// Track
        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.move(to: CGPoint(x: frame.minX + 173.5, y: frame.minY + 55.3))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 116, y: frame.minY + 70.65), controlPoint1: CGPoint(x: frame.minX + 152.56, y: frame.minY + 55.3), controlPoint2: CGPoint(x: frame.minX + 132.92, y: frame.minY + 60.89))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 58.3, y: frame.minY + 170.5), controlPoint1: CGPoint(x: frame.minX + 81.51, y: frame.minY + 90.56), controlPoint2: CGPoint(x: frame.minX + 58.3, y: frame.minY + 127.82))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 173.5, y: frame.minY + 285.7), controlPoint1: CGPoint(x: frame.minX + 58.3, y: frame.minY + 234.12), controlPoint2: CGPoint(x: frame.minX + 109.88, y: frame.minY + 285.7))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 288.7, y: frame.minY + 170.5), controlPoint1: CGPoint(x: frame.minX + 237.12, y: frame.minY + 285.7), controlPoint2: CGPoint(x: frame.minX + 288.7, y: frame.minY + 234.12))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 173.5, y: frame.minY + 55.3), controlPoint1: CGPoint(x: frame.minX + 288.7, y: frame.minY + 106.88), controlPoint2: CGPoint(x: frame.minX + 237.12, y: frame.minY + 55.3))
        bezierPath.close()
        bezierPath.move(to: CGPoint(x: frame.minX + 333.5, y: frame.minY + 170.5))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 173.5, y: frame.minY + 330.5), controlPoint1: CGPoint(x: frame.minX + 333.5, y: frame.minY + 258.87), controlPoint2: CGPoint(x: frame.minX + 261.87, y: frame.minY + 330.5))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 13.5, y: frame.minY + 170.5), controlPoint1: CGPoint(x: frame.minX + 85.13, y: frame.minY + 330.5), controlPoint2: CGPoint(x: frame.minX + 13.5, y: frame.minY + 258.87))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 77.16, y: frame.minY + 42.74), controlPoint1: CGPoint(x: frame.minX + 13.5, y: frame.minY + 118.31), controlPoint2: CGPoint(x: frame.minX + 38.49, y: frame.minY + 71.95))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 173.5, y: frame.minY + 10.5), controlPoint1: CGPoint(x: frame.minX + 103.96, y: frame.minY + 22.5), controlPoint2: CGPoint(x: frame.minX + 137.33, y: frame.minY + 10.5))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 333.5, y: frame.minY + 170.5), controlPoint1: CGPoint(x: frame.minX + 261.87, y: frame.minY + 10.5), controlPoint2: CGPoint(x: frame.minX + 333.5, y: frame.minY + 82.13))
        bezierPath.close()
        context.saveGState()
        bezierPath.addClip()
        let bezierBounds = bezierPath.cgPath.boundingBoxOfPath
        context.drawLinearGradient(MightyMetUI.redYellow,
            start: CGPoint(x: bezierBounds.midX, y: bezierBounds.minY),
            end: CGPoint(x: bezierBounds.midX, y: bezierBounds.maxY),
            options: [])
        context.restoreGState()




        //// PitchHandle Drawing
        context.saveGState()
        context.translateBy(x: frame.minX + 173.49, y: frame.minY + 170.13)
        context.rotate(by: -pitchAngle * CGFloat.pi/180)

        let pitchHandlePath = UIBezierPath(ovalIn: CGRect(x: -22.17, y: -158.4, width: 44.54, height: 42.62))
        MightyMetUI.transparent.setFill()
        pitchHandlePath.fill()
        MightyMetUI.lime.setStroke()
        pitchHandlePath.lineWidth = 3.5
        pitchHandlePath.stroke()

        context.restoreGState()


        //// BPMHandle Drawing
        context.saveGState()
        context.translateBy(x: frame.minX + 173.5, y: frame.minY + 170.86)
        context.rotate(by: -bPMAngle * CGFloat.pi/180)

        let bPMHandlePath = UIBezierPath(ovalIn: CGRect(x: -19.72, y: 115.27, width: 44.8, height: 44.79))
        MightyMetUI.transparent.setFill()
        bPMHandlePath.fill()
        MightyMetUI.electricBlue.setStroke()
        bPMHandlePath.lineWidth = 3.5
        bPMHandlePath.stroke()

        context.restoreGState()
    }

    public dynamic class func drawBPMSelector(frame: CGRect = CGRect(x: 0, y: 0, width: 310, height: 310), bPMAngle: CGFloat = 0, bPMText: String = "0") {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!


        //// Shadow Declarations
        let shadow = NSShadow()
        shadow.shadowColor = UIColor.darkGray.withAlphaComponent(0.8)
        shadow.shadowOffset = CGSize(width: 2, height: 2)
        shadow.shadowBlurRadius = 5


        //// Subframes
        let group: CGRect = CGRect(x: frame.minX + 11, y: frame.minY + frame.height - 299, width: 288, height: 288)


        //// Group
        //// Track
        context.saveGState()
        context.translateBy(x: group.minX + 144, y: group.minY + 144)



        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.move(to: CGPoint(x: 20, y: -124))
        bezier2Path.addCurve(to: CGPoint(x: 19.13, y: -118.15), controlPoint1: CGPoint(x: 20, y: -121.96), controlPoint2: CGPoint(x: 19.7, y: -120))
        bezier2Path.addCurve(to: CGPoint(x: 0.37, y: -104), controlPoint1: CGPoint(x: 16.66, y: -110.07), controlPoint2: CGPoint(x: 9.22, y: -104.17))
        bezier2Path.addLine(to: CGPoint(x: 0, y: -104))
        bezier2Path.addLine(to: CGPoint(x: 0, y: -103.68))
        bezier2Path.addCurve(to: CGPoint(x: -51.75, y: -89.86), controlPoint1: CGPoint(x: -18.85, y: -103.68), controlPoint2: CGPoint(x: -36.52, y: -98.65))
        bezier2Path.addCurve(to: CGPoint(x: -103.68, y: -0), controlPoint1: CGPoint(x: -82.79, y: -71.95), controlPoint2: CGPoint(x: -103.68, y: -38.41))
        bezier2Path.addCurve(to: CGPoint(x: -0, y: 103.68), controlPoint1: CGPoint(x: -103.68, y: 57.26), controlPoint2: CGPoint(x: -57.26, y: 103.68))
        bezier2Path.addCurve(to: CGPoint(x: 103.68, y: 0), controlPoint1: CGPoint(x: 57.26, y: 103.68), controlPoint2: CGPoint(x: 103.68, y: 57.26))
        bezier2Path.addCurve(to: CGPoint(x: 104, y: 0), controlPoint1: CGPoint(x: 103.68, y: 0), controlPoint2: CGPoint(x: 103.79, y: 0))
        bezier2Path.addCurve(to: CGPoint(x: 124, y: -20), controlPoint1: CGPoint(x: 104, y: -11.05), controlPoint2: CGPoint(x: 112.95, y: -20))
        bezier2Path.addCurve(to: CGPoint(x: 144, y: 0), controlPoint1: CGPoint(x: 135.05, y: -20), controlPoint2: CGPoint(x: 144, y: -11.05))
        bezier2Path.addCurve(to: CGPoint(x: -0, y: 144), controlPoint1: CGPoint(x: 144, y: 79.53), controlPoint2: CGPoint(x: 79.53, y: 144))
        bezier2Path.addCurve(to: CGPoint(x: -144, y: -0), controlPoint1: CGPoint(x: -79.53, y: 144), controlPoint2: CGPoint(x: -144, y: 79.53))
        bezier2Path.addCurve(to: CGPoint(x: -86.7, y: -114.98), controlPoint1: CGPoint(x: -144, y: -46.97), controlPoint2: CGPoint(x: -121.51, y: -88.7))
        bezier2Path.addCurve(to: CGPoint(x: 0, y: -144), controlPoint1: CGPoint(x: -62.59, y: -133.2), controlPoint2: CGPoint(x: -32.55, y: -144))
        bezier2Path.addCurve(to: CGPoint(x: 20, y: -124), controlPoint1: CGPoint(x: 11.05, y: -144), controlPoint2: CGPoint(x: 20, y: -135.05))
        bezier2Path.close()
        context.saveGState()
        bezier2Path.addClip()
        context.drawLinearGradient(MightyMetUI.redYellow, start: CGPoint(x: -114.66, y: -88.98), end: CGPoint(x: 88.98, y: 114.66), options: [])
        context.restoreGState()
        MightyMetUI.darkRed.setStroke()
        bezier2Path.lineWidth = 1
        bezier2Path.stroke()



        context.restoreGState()


        //// Handle
        context.saveGState()
        context.translateBy(x: group.minX + 144, y: group.minY + 144)

        context.setShadow(offset: shadow.shadowOffset, blur: shadow.shadowBlurRadius, color: (shadow.shadowColor as! UIColor).cgColor)
        context.beginTransparencyLayer(auxiliaryInfo: nil)


        //// BPMHandle Drawing
        context.saveGState()
        context.rotate(by: -(bPMAngle + 90) * CGFloat.pi/180)

        let bPMHandlePath = UIBezierPath(ovalIn: CGRect(x: -19.84, y: 105.64, width: 38.72, height: 38.17))
        MightyMetUI.transparent.setFill()
        bPMHandlePath.fill()
        UIColor.white.setStroke()
        bPMHandlePath.lineWidth = 3.5
        bPMHandlePath.stroke()

        context.restoreGState()


        context.endTransparencyLayer()

        context.restoreGState()


        //// TextLabel
        //// BPM Drawing
        let bPMRect = CGRect(x: group.minX + 53, y: group.minY + 113, width: 110, height: 61)
        context.saveGState()
        context.setShadow(offset: shadow.shadowOffset, blur: shadow.shadowBlurRadius, color: (shadow.shadowColor as! UIColor).cgColor)
        let bPMStyle = NSMutableParagraphStyle()
        bPMStyle.alignment = .right
        let bPMFontAttributes = [NSFontAttributeName: UIFont(name: "Avenir-Roman", size: 60)!, NSForegroundColorAttributeName: UIColor.white, NSParagraphStyleAttributeName: bPMStyle]

        let bPMTextHeight: CGFloat = bPMText.boundingRect(with: CGSize(width: bPMRect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: bPMFontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: bPMRect)
        bPMText.draw(in: CGRect(x: bPMRect.minX, y: bPMRect.minY + (bPMRect.height - bPMTextHeight) / 2, width: bPMRect.width, height: bPMTextHeight), withAttributes: bPMFontAttributes)
        context.restoreGState()
        context.restoreGState()



        //// BPM Label Drawing
        let bPMLabelRect = CGRect(x: group.minX + 168, y: group.minY + 119, width: 43, height: 21)
        let bPMLabelTextContent = "BPM"
        let bPMLabelStyle = NSMutableParagraphStyle()
        bPMLabelStyle.alignment = .left
        let bPMLabelFontAttributes = [NSFontAttributeName: UIFont(name: "Avenir-Light", size: UIFont.labelFontSize)!, NSForegroundColorAttributeName: UIColor.white, NSParagraphStyleAttributeName: bPMLabelStyle]

        let bPMLabelTextHeight: CGFloat = bPMLabelTextContent.boundingRect(with: CGSize(width: bPMLabelRect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: bPMLabelFontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: bPMLabelRect)
        bPMLabelTextContent.draw(in: CGRect(x: bPMLabelRect.minX, y: bPMLabelRect.minY + (bPMLabelRect.height - bPMLabelTextHeight) / 2, width: bPMLabelRect.width, height: bPMLabelTextHeight), withAttributes: bPMLabelFontAttributes)
        context.restoreGState()
    }

    public dynamic class func drawHertzSelector(frame: CGRect = CGRect(x: 0, y: 0, width: 200, height: 200), pitchAngle: CGFloat = 0, hertzText: String = "Name") {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!

        //// Color Declarations
        let purple = UIColor(red: 0.462, green: 0.000, blue: 1.000, alpha: 1.000)

        //// Gradient Declarations
        let bluePink = CGGradient(colorsSpace: nil, colors: [purple.cgColor, MightyMetUI.fuscia.cgColor] as CFArray, locations: [0, 1])!

        //// Shadow Declarations
        let shadow = NSShadow()
        shadow.shadowColor = UIColor.darkGray.withAlphaComponent(0.8)
        shadow.shadowOffset = CGSize(width: 2, height: 2)
        shadow.shadowBlurRadius = 5

        //// Track
        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.move(to: CGPoint(x: frame.minX + 188.99, y: frame.minY + 98.5))
        bezierPath.addLine(to: CGPoint(x: frame.minX + 160.99, y: frame.minY + 98.5))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 101, y: frame.minY + 39), controlPoint1: CGPoint(x: frame.minX + 160.46, y: frame.minY + 65.71), controlPoint2: CGPoint(x: frame.minX + 133.85, y: frame.minY + 39.27))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 101, y: frame.minY + 11.01), controlPoint1: CGPoint(x: frame.minX + 101, y: frame.minY + 25.98), controlPoint2: CGPoint(x: frame.minX + 101, y: frame.minY + 11.34))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 188.99, y: frame.minY + 98.5), controlPoint1: CGPoint(x: frame.minX + 149.19, y: frame.minY + 11.54), controlPoint2: CGPoint(x: frame.minX + 188.19, y: frame.minY + 50.37))
        bezierPath.close()
        bezierPath.move(to: CGPoint(x: frame.minX + 100, y: frame.minY + 11))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 100, y: frame.minY + 39), controlPoint1: CGPoint(x: frame.minX + 100, y: frame.minY + 11), controlPoint2: CGPoint(x: frame.minX + 100, y: frame.minY + 25.83))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 73.41, y: frame.minY + 45.39), controlPoint1: CGPoint(x: frame.minX + 90.45, y: frame.minY + 39.08), controlPoint2: CGPoint(x: frame.minX + 81.42, y: frame.minY + 41.37))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 71.72, y: frame.minY + 46.27), controlPoint1: CGPoint(x: frame.minX + 72.84, y: frame.minY + 45.67), controlPoint2: CGPoint(x: frame.minX + 72.28, y: frame.minY + 45.97))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 40, y: frame.minY + 99.5), controlPoint1: CGPoint(x: frame.minX + 52.83, y: frame.minY + 56.5), controlPoint2: CGPoint(x: frame.minX + 40, y: frame.minY + 76.5))
        bezierPath.addLine(to: CGPoint(x: frame.minX + 11.5, y: frame.minY + 99.5))
        bezierPath.addLine(to: CGPoint(x: frame.minX + 11.5, y: frame.minY + 100.5))
        bezierPath.addLine(to: CGPoint(x: frame.minX + 40.01, y: frame.minY + 100.5))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 100.5, y: frame.minY + 160), controlPoint1: CGPoint(x: frame.minX + 40.54, y: frame.minY + 133.45), controlPoint2: CGPoint(x: frame.minX + 67.42, y: frame.minY + 160))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 101.5, y: frame.minY + 159.99), controlPoint1: CGPoint(x: frame.minX + 100.83, y: frame.minY + 160), controlPoint2: CGPoint(x: frame.minX + 101.17, y: frame.minY + 160))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 101.5, y: frame.minY + 188.5), controlPoint1: CGPoint(x: frame.minX + 101.5, y: frame.minY + 173.98), controlPoint2: CGPoint(x: frame.minX + 101.5, y: frame.minY + 188.5))
        bezierPath.addLine(to: CGPoint(x: frame.minX + 102.5, y: frame.minY + 188.5))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 102.5, y: frame.minY + 159.97), controlPoint1: CGPoint(x: frame.minX + 102.5, y: frame.minY + 188.5), controlPoint2: CGPoint(x: frame.minX + 102.5, y: frame.minY + 173.96))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 161, y: frame.minY + 99.5), controlPoint1: CGPoint(x: frame.minX + 134.99, y: frame.minY + 158.91), controlPoint2: CGPoint(x: frame.minX + 161, y: frame.minY + 132.24))
        bezierPath.addLine(to: CGPoint(x: frame.minX + 189, y: frame.minY + 99.5))
        bezierPath.addLine(to: CGPoint(x: frame.minX + 189, y: frame.minY + 100))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 100, y: frame.minY + 189), controlPoint1: CGPoint(x: frame.minX + 189, y: frame.minY + 149.15), controlPoint2: CGPoint(x: frame.minX + 149.15, y: frame.minY + 189))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 11, y: frame.minY + 100), controlPoint1: CGPoint(x: frame.minX + 50.85, y: frame.minY + 189), controlPoint2: CGPoint(x: frame.minX + 11, y: frame.minY + 149.15))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 44.47, y: frame.minY + 30.44), controlPoint1: CGPoint(x: frame.minX + 11, y: frame.minY + 71.85), controlPoint2: CGPoint(x: frame.minX + 24.07, y: frame.minY + 46.75))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 50, y: frame.minY + 26.36), controlPoint1: CGPoint(x: frame.minX + 46.26, y: frame.minY + 29.01), controlPoint2: CGPoint(x: frame.minX + 48.1, y: frame.minY + 27.65))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 53.14, y: frame.minY + 24.32), controlPoint1: CGPoint(x: frame.minX + 51.03, y: frame.minY + 25.66), controlPoint2: CGPoint(x: frame.minX + 52.08, y: frame.minY + 24.98))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 98.47, y: frame.minY + 11.01), controlPoint1: CGPoint(x: frame.minX + 66.35, y: frame.minY + 16.13), controlPoint2: CGPoint(x: frame.minX + 81.85, y: frame.minY + 11.29))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 100, y: frame.minY + 11), controlPoint1: CGPoint(x: frame.minX + 99.03, y: frame.minY + 11), controlPoint2: CGPoint(x: frame.minX + 99.51, y: frame.minY + 11))
        bezierPath.addLine(to: CGPoint(x: frame.minX + 100, y: frame.minY + 11))
        bezierPath.close()
        context.saveGState()
        bezierPath.addClip()
        let bezierBounds = bezierPath.cgPath.boundingBoxOfPath
        context.drawLinearGradient(bluePink,
            start: CGPoint(x: bezierBounds.midX, y: bezierBounds.maxY),
            end: CGPoint(x: bezierBounds.midX, y: bezierBounds.minY),
            options: [])
        context.restoreGState()
        MightyMetUI.darkRed.setStroke()
        bezierPath.lineWidth = 1
        bezierPath.stroke()




        //// Handle
        context.saveGState()
        context.setShadow(offset: shadow.shadowOffset, blur: shadow.shadowBlurRadius, color: (shadow.shadowColor as! UIColor).cgColor)
        context.beginTransparencyLayer(auxiliaryInfo: nil)


        //// BPMHandle Drawing
        context.saveGState()
        context.translateBy(x: frame.minX + 100, y: frame.minY + 100)
        context.rotate(by: -(pitchAngle + 90) * CGFloat.pi/180)

        let bPMHandlePath = UIBezierPath(ovalIn: CGRect(x: -13.84, y: 61, width: 27.84, height: 27.82))
        MightyMetUI.transparent.setFill()
        bPMHandlePath.fill()
        UIColor.white.setStroke()
        bPMHandlePath.lineWidth = 3.5
        bPMHandlePath.stroke()

        context.restoreGState()


        context.endTransparencyLayer()
        context.restoreGState()


        //// Labels
        //// Hertz Value Drawing
        let hertzValueRect = CGRect(x: frame.minX + 40, y: frame.minY + 65, width: 120, height: 49)
        context.saveGState()
        context.setShadow(offset: shadow.shadowOffset, blur: shadow.shadowBlurRadius, color: (shadow.shadowColor as! UIColor).cgColor)
        let hertzValueStyle = NSMutableParagraphStyle()
        hertzValueStyle.alignment = .center
        let hertzValueFontAttributes = [NSFontAttributeName: UIFont(name: "Avenir-Roman", size: 32)!, NSForegroundColorAttributeName: UIColor.white, NSParagraphStyleAttributeName: hertzValueStyle]

        let hertzValueTextHeight: CGFloat = hertzText.boundingRect(with: CGSize(width: hertzValueRect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: hertzValueFontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: hertzValueRect)
        hertzText.draw(in: CGRect(x: hertzValueRect.minX, y: hertzValueRect.minY + (hertzValueRect.height - hertzValueTextHeight) / 2, width: hertzValueRect.width, height: hertzValueTextHeight), withAttributes: hertzValueFontAttributes)
        context.restoreGState()
        context.restoreGState()



        //// Herts Label Drawing
        let hertsLabelRect = CGRect(x: frame.minX + 72, y: frame.minY + 114, width: 56, height: 21)
        let hertsLabelTextContent = "sound"
        let hertsLabelStyle = NSMutableParagraphStyle()
        hertsLabelStyle.alignment = .center
        let hertsLabelFontAttributes = [NSFontAttributeName: UIFont(name: "Avenir-Light", size: 20)!, NSForegroundColorAttributeName: UIColor.white, NSParagraphStyleAttributeName: hertsLabelStyle]

        let hertsLabelTextHeight: CGFloat = hertsLabelTextContent.boundingRect(with: CGSize(width: hertsLabelRect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: hertsLabelFontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: hertsLabelRect)
        hertsLabelTextContent.draw(in: CGRect(x: hertsLabelRect.minX, y: hertsLabelRect.minY + (hertsLabelRect.height - hertsLabelTextHeight) / 2, width: hertsLabelRect.width, height: hertsLabelTextHeight), withAttributes: hertsLabelFontAttributes)
        context.restoreGState()
    }

    public dynamic class func drawPlayButton(frame: CGRect = CGRect(x: 7, y: 7, width: 86, height: 86), isRunning: Bool = false, isNotRunning: Bool = true) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        // This non-generic function dramatically improves compilation times of complex expressions.
        func fastFloor(_ x: CGFloat) -> CGFloat { return floor(x) }


        //// Shadow Declarations
        let shadow = NSShadow()
        shadow.shadowColor = UIColor.darkGray.withAlphaComponent(0.8)
        shadow.shadowOffset = CGSize(width: 2, height: 2)
        shadow.shadowBlurRadius = 5


        //// Subframes
        let play: CGRect = CGRect(x: frame.minX + fastFloor((frame.width - 69) * 0.52941 + 0.5), y: frame.minY + fastFloor((frame.height - 69) * 0.47059 + 0.5), width: 69, height: 69)


        //// Play
        context.saveGState()
        context.setShadow(offset: shadow.shadowOffset, blur: shadow.shadowBlurRadius, color: (shadow.shadowColor as! UIColor).cgColor)
        context.beginTransparencyLayer(auxiliaryInfo: nil)


        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.move(to: CGPoint(x: play.minX + 34.5, y: play.minY + 6))
        bezierPath.addCurve(to: CGPoint(x: play.minX + 18.96, y: play.minY + 10.61), controlPoint1: CGPoint(x: play.minX + 28.77, y: play.minY + 6), controlPoint2: CGPoint(x: play.minX + 23.43, y: play.minY + 7.69))
        bezierPath.addCurve(to: CGPoint(x: play.minX + 6, y: play.minY + 34.5), controlPoint1: CGPoint(x: play.minX + 11.16, y: play.minY + 15.69), controlPoint2: CGPoint(x: play.minX + 6, y: play.minY + 24.49))
        bezierPath.addCurve(to: CGPoint(x: play.minX + 34.5, y: play.minY + 63), controlPoint1: CGPoint(x: play.minX + 6, y: play.minY + 50.24), controlPoint2: CGPoint(x: play.minX + 18.76, y: play.minY + 63))
        bezierPath.addCurve(to: CGPoint(x: play.minX + 63, y: play.minY + 34.5), controlPoint1: CGPoint(x: play.minX + 50.24, y: play.minY + 63), controlPoint2: CGPoint(x: play.minX + 63, y: play.minY + 50.24))
        bezierPath.addCurve(to: CGPoint(x: play.minX + 34.5, y: play.minY + 6), controlPoint1: CGPoint(x: play.minX + 63, y: play.minY + 18.76), controlPoint2: CGPoint(x: play.minX + 50.24, y: play.minY + 6))
        bezierPath.close()
        bezierPath.move(to: CGPoint(x: play.minX + 69, y: play.minY + 34.5))
        bezierPath.addCurve(to: CGPoint(x: play.minX + 34.5, y: play.minY + 69), controlPoint1: CGPoint(x: play.minX + 69, y: play.minY + 53.55), controlPoint2: CGPoint(x: play.minX + 53.55, y: play.minY + 69))
        bezierPath.addCurve(to: CGPoint(x: play.minX, y: play.minY + 34.5), controlPoint1: CGPoint(x: play.minX + 15.45, y: play.minY + 69), controlPoint2: CGPoint(x: play.minX, y: play.minY + 53.55))
        bezierPath.addCurve(to: CGPoint(x: play.minX + 13.66, y: play.minY + 7.01), controlPoint1: CGPoint(x: play.minX, y: play.minY + 23.28), controlPoint2: CGPoint(x: play.minX + 5.36, y: play.minY + 13.31))
        bezierPath.addCurve(to: CGPoint(x: play.minX + 34.5, y: play.minY), controlPoint1: CGPoint(x: play.minX + 19.45, y: play.minY + 2.61), controlPoint2: CGPoint(x: play.minX + 26.67, y: play.minY))
        bezierPath.addCurve(to: CGPoint(x: play.minX + 69, y: play.minY + 34.5), controlPoint1: CGPoint(x: play.minX + 53.55, y: play.minY), controlPoint2: CGPoint(x: play.minX + 69, y: play.minY + 15.45))
        bezierPath.close()
        MightyMetUI.transparent.setFill()
        bezierPath.fill()


        if (isNotRunning) {
            //// Bezier 2 Drawing
            let bezier2Path = UIBezierPath()
            bezier2Path.move(to: CGPoint(x: play.minX + 25, y: play.minY + 15))
            bezier2Path.addLine(to: CGPoint(x: play.minX + 53, y: play.minY + 33))
            bezier2Path.addLine(to: CGPoint(x: play.minX + 25, y: play.minY + 54))
            bezier2Path.addLine(to: CGPoint(x: play.minX + 25, y: play.minY + 15))
            bezier2Path.close()
            MightyMetUI.transparent.setFill()
            bezier2Path.fill()
        }


        if (isRunning) {
            //// Pause
            //// Rectangle Drawing
            let rectanglePath = UIBezierPath(rect: CGRect(x: play.minX + 23, y: play.minY + 19, width: 8, height: 31))
            MightyMetUI.yellowOrange.setFill()
            rectanglePath.fill()


            //// Rectangle 2 Drawing
            let rectangle2Path = UIBezierPath(rect: CGRect(x: play.minX + 37, y: play.minY + 19, width: 8, height: 31))
            MightyMetUI.yellowOrange.setFill()
            rectangle2Path.fill()


        }


        context.endTransparencyLayer()
        context.restoreGState()
    }

    public dynamic class func drawPlaylistButton(frame: CGRect = CGRect(x: 7, y: 6, width: 87, height: 88)) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        // This non-generic function dramatically improves compilation times of complex expressions.
        func fastFloor(_ x: CGFloat) -> CGFloat { return floor(x) }


        //// Shadow Declarations
        let shadow = NSShadow()
        shadow.shadowColor = UIColor.darkGray.withAlphaComponent(0.8)
        shadow.shadowOffset = CGSize(width: 2, height: 2)
        shadow.shadowBlurRadius = 5


        //// Subframes
        let playlist: CGRect = CGRect(x: frame.minX + fastFloor((frame.width - 69) * 0.50000 + 0.5), y: frame.minY + fastFloor((frame.height - 69) * 0.47368 + 0.5), width: 69, height: 69)


        //// Playlist
        context.saveGState()
        context.setShadow(offset: shadow.shadowOffset, blur: shadow.shadowBlurRadius, color: (shadow.shadowColor as! UIColor).cgColor)
        context.beginTransparencyLayer(auxiliaryInfo: nil)


        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.move(to: CGPoint(x: playlist.minX + 34.5, y: playlist.minY + 6))
        bezierPath.addCurve(to: CGPoint(x: playlist.minX + 18.96, y: playlist.minY + 10.61), controlPoint1: CGPoint(x: playlist.minX + 28.77, y: playlist.minY + 6), controlPoint2: CGPoint(x: playlist.minX + 23.43, y: playlist.minY + 7.69))
        bezierPath.addCurve(to: CGPoint(x: playlist.minX + 6, y: playlist.minY + 34.5), controlPoint1: CGPoint(x: playlist.minX + 11.16, y: playlist.minY + 15.69), controlPoint2: CGPoint(x: playlist.minX + 6, y: playlist.minY + 24.49))
        bezierPath.addCurve(to: CGPoint(x: playlist.minX + 34.5, y: playlist.minY + 63), controlPoint1: CGPoint(x: playlist.minX + 6, y: playlist.minY + 50.24), controlPoint2: CGPoint(x: playlist.minX + 18.76, y: playlist.minY + 63))
        bezierPath.addCurve(to: CGPoint(x: playlist.minX + 63, y: playlist.minY + 34.5), controlPoint1: CGPoint(x: playlist.minX + 50.24, y: playlist.minY + 63), controlPoint2: CGPoint(x: playlist.minX + 63, y: playlist.minY + 50.24))
        bezierPath.addCurve(to: CGPoint(x: playlist.minX + 34.5, y: playlist.minY + 6), controlPoint1: CGPoint(x: playlist.minX + 63, y: playlist.minY + 18.76), controlPoint2: CGPoint(x: playlist.minX + 50.24, y: playlist.minY + 6))
        bezierPath.close()
        bezierPath.move(to: CGPoint(x: playlist.minX + 69, y: playlist.minY + 34.5))
        bezierPath.addCurve(to: CGPoint(x: playlist.minX + 34.5, y: playlist.minY + 69), controlPoint1: CGPoint(x: playlist.minX + 69, y: playlist.minY + 53.55), controlPoint2: CGPoint(x: playlist.minX + 53.55, y: playlist.minY + 69))
        bezierPath.addCurve(to: CGPoint(x: playlist.minX, y: playlist.minY + 34.5), controlPoint1: CGPoint(x: playlist.minX + 15.45, y: playlist.minY + 69), controlPoint2: CGPoint(x: playlist.minX, y: playlist.minY + 53.55))
        bezierPath.addCurve(to: CGPoint(x: playlist.minX + 13.66, y: playlist.minY + 7.01), controlPoint1: CGPoint(x: playlist.minX, y: playlist.minY + 23.28), controlPoint2: CGPoint(x: playlist.minX + 5.36, y: playlist.minY + 13.31))
        bezierPath.addCurve(to: CGPoint(x: playlist.minX + 34.5, y: playlist.minY), controlPoint1: CGPoint(x: playlist.minX + 19.45, y: playlist.minY + 2.61), controlPoint2: CGPoint(x: playlist.minX + 26.67, y: playlist.minY))
        bezierPath.addCurve(to: CGPoint(x: playlist.minX + 69, y: playlist.minY + 34.5), controlPoint1: CGPoint(x: playlist.minX + 53.55, y: playlist.minY), controlPoint2: CGPoint(x: playlist.minX + 69, y: playlist.minY + 15.45))
        bezierPath.close()
        MightyMetUI.transparent.setFill()
        bezierPath.fill()


        //// Group
        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(rect: CGRect(x: playlist.minX + 19, y: playlist.minY + 23, width: 31, height: 3))
        MightyMetUI.transparent.setFill()
        rectanglePath.fill()


        //// Rectangle 2 Drawing
        let rectangle2Path = UIBezierPath(rect: CGRect(x: playlist.minX + 19, y: playlist.minY + 30, width: 31, height: 3))
        MightyMetUI.transparent.setFill()
        rectangle2Path.fill()


        //// Rectangle 3 Drawing
        let rectangle3Path = UIBezierPath(rect: CGRect(x: playlist.minX + 19, y: playlist.minY + 37, width: 31, height: 3))
        MightyMetUI.transparent.setFill()
        rectangle3Path.fill()


        //// Rectangle 4 Drawing
        let rectangle4Path = UIBezierPath(rect: CGRect(x: playlist.minX + 19, y: playlist.minY + 44, width: 31, height: 3))
        MightyMetUI.transparent.setFill()
        rectangle4Path.fill()




        context.endTransparencyLayer()
        context.restoreGState()
    }

    public dynamic class func drawTempoLight(frame: CGRect = CGRect(x: 0, y: 0, width: 100, height: 100), flash: Bool = false) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        // This non-generic function dramatically improves compilation times of complex expressions.
        func fastFloor(_ x: CGFloat) -> CGFloat { return floor(x) }


        //// Gradient Declarations
        let darkRedWhite = CGGradient(colorsSpace: nil, colors: [MightyMetUI.darkRed.cgColor, MightyMetUI.darkRed.blended(withFraction: 0.5, of: MightyMetUI.darkRedWhiteColor).cgColor, MightyMetUI.darkRedWhiteColor.cgColor, MightyMetUI.darkRedWhiteColor.blended(withFraction: 0.5, of: UIColor.white).cgColor, UIColor.white.cgColor] as CFArray, locations: [0, 0.31, 0.84, 0.99, 1])!
        let darkRedWhiteOn = CGGradient(colorsSpace: nil, colors: [MightyMetUI.darkRedWhiteOnColor.cgColor, MightyMetUI.darkRedWhiteOnColor.blended(withFraction: 0.5, of: MightyMetUI.darkRedWhiteColor).cgColor, MightyMetUI.darkRedWhiteColor.cgColor, MightyMetUI.darkRedWhiteColor.blended(withFraction: 0.5, of: UIColor.white).cgColor, UIColor.white.cgColor] as CFArray, locations: [0, 0.42, 0.62, 0.98, 1])!


        //// Subframes
        let group: CGRect = CGRect(x: frame.minX + 8, y: frame.minY + 7, width: frame.width - 15, height: frame.height - 15)


        //// Group
        //// Off
        //// Oval Drawing
        let ovalRect = CGRect(x: group.minX + fastFloor(group.width * 0.00000 + 0.5), y: group.minY + fastFloor(group.height * 0.00000 + 0.5), width: fastFloor(group.width * 1.00000 + 0.5) - fastFloor(group.width * 0.00000 + 0.5), height: fastFloor(group.height * 1.00000 + 0.5) - fastFloor(group.height * 0.00000 + 0.5))
        let ovalPath = UIBezierPath(ovalIn: ovalRect)
        context.saveGState()
        ovalPath.addClip()
        let ovalResizeRatio: CGFloat = min(ovalRect.width / 85, ovalRect.height / 85)
        context.drawRadialGradient(darkRedWhite,
            startCenter: CGPoint(x: ovalRect.midX + 0 * ovalResizeRatio, y: ovalRect.midY + 0 * ovalResizeRatio), startRadius: 43.92 * ovalResizeRatio,
            endCenter: CGPoint(x: ovalRect.midX + -19.88 * ovalResizeRatio, y: ovalRect.midY + -16.17 * ovalResizeRatio), endRadius: 0.33 * ovalResizeRatio,
            options: [.drawsBeforeStartLocation, .drawsAfterEndLocation])
        context.restoreGState()
        UIColor.black.setStroke()
        ovalPath.lineWidth = 1
        ovalPath.stroke()




        if (flash) {
            //// On
            //// Oval 2 Drawing
            let oval2Rect = CGRect(x: group.minX + fastFloor(group.width * 0.00000 + 0.5), y: group.minY + fastFloor(group.height * 0.00000 + 0.5), width: fastFloor(group.width * 1.00000 + 0.5) - fastFloor(group.width * 0.00000 + 0.5), height: fastFloor(group.height * 1.00000 + 0.5) - fastFloor(group.height * 0.00000 + 0.5))
            let oval2Path = UIBezierPath(ovalIn: oval2Rect)
            context.saveGState()
            oval2Path.addClip()
            let oval2ResizeRatio: CGFloat = min(oval2Rect.width / 85, oval2Rect.height / 85)
            context.drawRadialGradient(darkRedWhiteOn,
                startCenter: CGPoint(x: oval2Rect.midX + 0 * oval2ResizeRatio, y: oval2Rect.midY + 0 * oval2ResizeRatio), startRadius: 43.92 * oval2ResizeRatio,
                endCenter: CGPoint(x: oval2Rect.midX + -19.88 * oval2ResizeRatio, y: oval2Rect.midY + -16.17 * oval2ResizeRatio), endRadius: 0.33 * oval2ResizeRatio,
                options: [.drawsBeforeStartLocation, .drawsAfterEndLocation])
            context.restoreGState()
            UIColor.black.setStroke()
            oval2Path.lineWidth = 1
            oval2Path.stroke()


        }
    }

}



extension UIColor {
    func withHue(_ newHue: CGFloat) -> UIColor {
        var saturation: CGFloat = 1, brightness: CGFloat = 1, alpha: CGFloat = 1
        self.getHue(nil, saturation: &saturation, brightness: &brightness, alpha: &alpha)
        return UIColor(hue: newHue, saturation: saturation, brightness: brightness, alpha: alpha)
    }
    func withSaturation(_ newSaturation: CGFloat) -> UIColor {
        var hue: CGFloat = 1, brightness: CGFloat = 1, alpha: CGFloat = 1
        self.getHue(&hue, saturation: nil, brightness: &brightness, alpha: &alpha)
        return UIColor(hue: hue, saturation: newSaturation, brightness: brightness, alpha: alpha)
    }
    func withBrightness(_ newBrightness: CGFloat) -> UIColor {
        var hue: CGFloat = 1, saturation: CGFloat = 1, alpha: CGFloat = 1
        self.getHue(&hue, saturation: &saturation, brightness: nil, alpha: &alpha)
        return UIColor(hue: hue, saturation: saturation, brightness: newBrightness, alpha: alpha)
    }
    func withAlpha(_ newAlpha: CGFloat) -> UIColor {
        var hue: CGFloat = 1, saturation: CGFloat = 1, brightness: CGFloat = 1
        self.getHue(&hue, saturation: &saturation, brightness: &brightness, alpha: nil)
        return UIColor(hue: hue, saturation: saturation, brightness: brightness, alpha: newAlpha)
    }
    func highlight(withLevel highlight: CGFloat) -> UIColor {
        var red: CGFloat = 1, green: CGFloat = 1, blue: CGFloat = 1, alpha: CGFloat = 1
        self.getRed(&red, green: &green, blue: &blue, alpha: &alpha)
        return UIColor(red: red * (1-highlight) + highlight, green: green * (1-highlight) + highlight, blue: blue * (1-highlight) + highlight, alpha: alpha * (1-highlight) + highlight)
    }
    func shadow(withLevel shadow: CGFloat) -> UIColor {
        var red: CGFloat = 1, green: CGFloat = 1, blue: CGFloat = 1, alpha: CGFloat = 1
        self.getRed(&red, green: &green, blue: &blue, alpha: &alpha)
        return UIColor(red: red * (1-shadow), green: green * (1-shadow), blue: blue * (1-shadow), alpha: alpha * (1-shadow) + shadow)
    }
    func blended(withFraction fraction: CGFloat, of color: UIColor) -> UIColor {
        var r1: CGFloat = 1, g1: CGFloat = 1, b1: CGFloat = 1, a1: CGFloat = 1
        var r2: CGFloat = 1, g2: CGFloat = 1, b2: CGFloat = 1, a2: CGFloat = 1

        self.getRed(&r1, green: &g1, blue: &b1, alpha: &a1)
        color.getRed(&r2, green: &g2, blue: &b2, alpha: &a2)

        return UIColor(red: r1 * (1 - fraction) + r2 * fraction,
            green: g1 * (1 - fraction) + g2 * fraction,
            blue: b1 * (1 - fraction) + b2 * fraction,
            alpha: a1 * (1 - fraction) + a2 * fraction);
    }
}
